import { Router, Response } from 'express';
import { supabase } from '../lib/supabase';
import { AuthRequest } from '../middleware/auth';

export const invoicesRouter = Router();

// GET /invoices
invoicesRouter.get('/', async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { search, status, customer_id, from, to } = req.query;
    let query = supabase
      .from('invoices')
      .select('*, customer:customers(id, name, phone), items:invoice_items(*)')
      .order('created_at', { ascending: false });

    if (search) query = query.or(`invoice_number.ilike.%${search}%`);
    if (status) query = query.eq('status', status);
    if (customer_id) query = query.eq('customer_id', customer_id);
    if (from) query = query.gte('created_at', from);
    if (to) query = query.lte('created_at', `${to}T23:59:59`);

    const { data, error } = await query;
    if (error) throw error;
    res.json({ success: true, data: data || [] });
  } catch (err: any) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// GET /invoices/:id
invoicesRouter.get('/:id', async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { data, error } = await supabase
      .from('invoices')
      .select('*, customer:customers(*), branch:branches(id, name), items:invoice_items(*, product:products(id, name))')
      .eq('id', req.params.id)
      .single();
    if (error) throw error;
    res.json({ success: true, data });
  } catch (err: any) {
    res.status(500).json({ success: false, message: err.message });
  }
});

// POST /invoices
invoicesRouter.post('/', async (req: AuthRequest, res: Response): Promise<void> => {
  try {
    const { customer_id, payment_type, paid_amount = 0, notes, items } = req.body;

    if (!customer_id || !items || items.length === 0) {
      res.status(400).json({ success: false, message: 'العميل والأصناف مطلوبة' });
      return;
    }

    // Validate items and check stock
    for (const item of items) {
      if (!item.product_id || !item.quantity_units || item.quantity_units <= 0) {
        res.status(400).json({ success: false, message: 'بيانات الأصناف غير صحيحة' });
        return;
      }

      // Check stock
      const { data: inv } = await supabase
        .from('inventory')
        .select('quantity')
        .eq('product_id', item.product_id)
        .eq('branch_id', req.user!.branch_id)
        .single();

      if (!inv || inv.quantity < item.quantity_units) {
        const { data: prod } = await supabase.from('products').select('name').eq('id', item.product_id).single();
        res.status(400).json({ success: false, message: `المخزون غير كافي للصنف: ${prod?.name}` });
        return;
      }
    }

    // Calculate total
    const total = items.reduce((sum: number, item: any) =>
      sum + Math.round(item.pharmacist_price * item.quantity_units * 100) / 100, 0);
    const actualPaid = Math.min(Number(paid_amount) || 0, total);

    // Get branch_id
    const branch_id = req.user!.branch_id;

    // Create invoice
    const { data: invoice, error: invError } = await supabase.from('invoices').insert({
      invoice_number: '', // Will be generated by trigger
      customer_id,
      branch_id,
      payment_type,
      total,
      subtotal: total,
      paid_amount: actualPaid,
      notes: notes || null,
      created_by: req.user!.id,
    }).select().single();

    if (invError) throw invError;

    // Insert items
    const invoiceItems = items.map((item: any) => ({
      invoice_id: invoice.id,
      product_id: item.product_id,
      product_name: item.product_name,
      is_box: item.is_box || false,
      box_quantity: item.box_quantity || 1,
      quantity: Number(item.quantity),
      quantity_units: Number(item.quantity_units),
      public_price: Number(item.public_price),
      pharmacist_price: Number(item.pharmacist_price),
      total: Math.round(Number(item.pharmacist_price) * Number(item.quantity_units) * 100) / 100,
    }));

    const { error: itemsError } = await supabase.from('invoice_items').insert(invoiceItems);
    if (itemsError) throw itemsError;

    // Deduct from inventory & record movements
    for (const item of items) {
      // Get current quantity
      const { data: currentInv } = await supabase
        .from('inventory')
        .select('quantity')
        .eq('product_id', item.product_id)
        .eq('branch_id', branch_id)
        .single();

      const newQty = (currentInv?.quantity || 0) - item.quantity_units;

      await supabase.from('inventory')
        .update({ quantity: newQty })
        .eq('product_id', item.product_id)
        .eq('branch_id', branch_id);

      await supabase.from('inventory_movements').insert({
        product_id: item.product_id,
        branch_id,
        movement_type: 'out',
        quantity: item.quantity_units,
        quantity_before: currentInv?.quantity || 0,
        quantity_after: newQty,
        reference_type: 'invoice',
        reference_id: invoice.id,
        notes: `فاتورة بيع ${invoice.invoice_number}`,
        created_by: req.user!.id,
      });
    }

    // Update customer debt if credit
    if (invoice.remaining > 0) {
      await supabase.rpc('increment_customer_debt', {
        p_customer_id: customer_id,
        p_amount: invoice.remaining,
      }).catch(() => {
        // Fallback if function doesn't exist
        return supabase
          .from('customers')
          .select('total_debt')
          .eq('id', customer_id)
          .single()
          .then(({ data: cust }) => {
            return supabase.from('customers').update({ total_debt: (cust?.total_debt || 0) + invoice.remaining }).eq('id', customer_id);
          });
      });
    }

    // Record cash box entry for paid amount
    if (actualPaid > 0) {
      await supabase.from('cash_box').insert({
        transaction_type: 'in',
        amount: actualPaid,
        source: 'invoice',
        reference_id: invoice.id,
        reference_number: invoice.invoice_number,
        description: `مبيعات فاتورة ${invoice.invoice_number}`,
        branch_id,
        created_by: req.user!.id,
      });
    }

    // Fetch complete invoice
    const { data: fullInvoice } = await supabase
      .from('invoices')
      .select('*, customer:customers(*), items:invoice_items(*)')
      .eq('id', invoice.id)
      .single();

    res.status(201).json({ success: true, data: fullInvoice });
  } catch (err: any) {
    res.status(500).json({ success: false, message: err.message });
  }
});
